http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  candidates:
    host: localhost
    paths: ['/candidates*']
serviceEndpoints:
  candidates:
    url: 'http://localhost:3010/api'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - candidates
    policies:
      - oauth2:
        -
          action:
            jwt:
              issuer: jobs-gateway
              audience: finalusers
              subject: test1
              secretOrPublicKey: ssssst
              checkCredentialExistence: false
      - rate-limit:
        - 
          action:                         # allow
            max: 10                      # max 10 request
            windowMs: 120000              # per 120 seconds
            rateLimitBy: "${req.user.id}" # EgContext.req.user.id
            delayAfter: 0
            delayMs: 0 
      - proxy:
          - action:
              serviceEndpoint: candidates 
              changeOrigin: false
     
